Allow blobs to have dependancies.
shakenfist/shakenfist pull request #1208
Opened 2022-01-04 00:54 UTC by mikalstill

This is needed to for docker images, which are naturally a series of layers, but also makes sense for VM images when we want thin snapshots.

2022-01-04 00:55 UTC, mikalstill commented
This is still a work in progress, I need to add the API calls to create a thin snapshot, ensure that a VM can be constructed with a non-trivial list of dependant blobs (I suspect I need to add more backing file entries to the libvirt template), and needs some solid CI testing.

2022-01-08 08:44 UTC, mikalstill commented
@mandoonandy, I think this is ready for review as a logical boundary on my adventures. I propose this would stay in develop until 0.6, so landing this implies that other things we want in 0.5 releases would need to be backported.

2022-01-08 10:07 UTC, mandoonandy requested changes
Looks good, minor questions

2022-01-08 10:48 UTC, mikalstill commented on shakenfist/blob.py
> +    # the blob used to start an instance has been deleted already.
I kind of meant this comment as a hedge. We do reference count the dependancies, so this should not occur except in an exceptional case.

2022-01-08 21:57 UTC, mikalstill commented on shakenfist/blob.py
> +from shakenfist.exceptions import BlobDeleted, BlobFetchFailed, BlobDependancyMissing
Done.

2022-01-08 21:58 UTC, mikalstill commented on shakenfist/blob.py
> +            is_transcode_of=None):
Done, but I decided I liked `transcodes`.

2022-01-08 21:59 UTC, mikalstill commented on shakenfist/client/upgrade.py
> +                if b.get('version') == 2:
I think this is a more general question we should deal with outside this branch -- when do we start supporting online upgrades? How do we support them? What do we do with old versions of SF that are running during the upgrade and need the old version?

2022-01-08 22:04 UTC, mikalstill commented on shakenfist/images.py
> +            if cluster_size_as_int.endswith('M'):
Done.

2022-01-09 03:05 UTC, mandoonandy commented on shakenfist/blob.py
> +    # Check that the dependancy (if any) actually exists. This test can fail when
dependency

2022-01-09 03:06 UTC, mandoonandy approved these changes
LGTM

2022-01-09 22:08 UTC, merged