Handle blank databases during install.
shakenfist/shakenfist pull request #332
Opened 2020-09-29 00:02 UTC by mikalstill

Fixes #331.

2020-09-29 01:23 UTC, mandoonandy requested changes

2020-09-29 01:23 UTC, mandoonandy commented on shakenfist/client/upgrade.py
> +    if len(versions) == 0:
[PEP8 Nazi] To be pythonic this should be `if not versions:` [/PEP8 Nazi]
I'm surprised the linter did not have a whinge.

2020-09-29 04:10 UTC, mikalstill commented
I'm testing a fix for #333 at the moment, I'll circle back to this one once that's done.

2020-09-30 11:17 UTC, mandoonandy approved these changes
LGTM

2020-09-30 11:17 UTC, merged