Add an operation description to locks and log it in etcd.
shakenfist/shakenfist pull request #458
Opened 2020-10-23 09:41 UTC by mikalstill

Fixes #455 except for the client side.

2020-10-23 22:33 UTC, mandoonandy requested changes
Typo is the main problem.

You mentioned variable naming a couple of days ago (one of the "two most difficult coding problems"). Would you consider changing `operation` to `op` to reduce verbosity?

2020-10-23 22:33 UTC, mandoonandy commented on shakenfist/db.py
> +    with etcd.get_lock('vxlan', None, 'all', opertaion='Allocate network'):
lol. I think we need some unit tests.

2020-10-24 02:28 UTC, mikalstill commented on shakenfist/db.py
> +    with etcd.get_lock('vxlan', None, 'all', opertaion='Allocate network'):
Lies! Also yes.

2020-10-25 07:04 UTC, mandoonandy approved these changes
Thanks. LGTM

2020-10-25 07:04 UTC, merged