Stop constantly rebuilding DHCP services.
shakenfist/shakenfist pull request #713
Opened 2021-03-01 09:51 UTC by mikalstill

Fixes #711.

2021-03-01 09:57 UTC, mandoonandy commented
What happened to the unit tests?

2021-03-02 03:14 UTC, mandoonandy requested changes

2021-03-02 03:14 UTC, mandoonandy commented on deploy/shakenfist_ci/tests/test_floating_ips.py
> +                if out.find('Floating IPs work!'):
should this check for != -1?

2021-03-02 03:27 UTC, mikalstill commented on deploy/shakenfist_ci/tests/test_floating_ips.py
> +                if out.find('Floating IPs work!'):
Fair point.

2021-03-02 04:09 UTC, mandoonandy approved these changes
LGTM

2021-03-02 04:56 UTC, merged