Refactor image resolvers, and minor fixes found while adding the CentOS resolver
shakenfist/shakenfist pull request #781
Opened 2021-05-02 08:58 UTC by mikalstill

2021-05-02 22:53 UTC, mandoonandy requested changes
Couple of tiny comments to prove I looked at the code.

2021-05-02 22:53 UTC, mandoonandy commented on shakenfist/baseobject.py
> +                    'targets', self.state_targets).debug('Verifying state transition')
This could be less verbose using `with_fields()`?

2021-05-02 22:53 UTC, mandoonandy commented on shakenfist/image_resolver/debian.py
> +        return (url, None)
Would this be better here?
```
return (url, checksum if checksum else None)
```

2021-05-02 22:53 UTC, mandoonandy commented on shakenfist/image_resolver/ubuntu.py
> +        return (url, None)
as above, using `if`

2021-05-02 22:53 UTC, mandoonandy commented on shakenfist/images.py
> +        # Handle URL shortcut with built-in , '
missed enter, hit `'`?

2021-05-03 07:55 UTC, mikalstill commented on shakenfist/image_resolver/debian.py
> +        return (url, None)
Done.

2021-05-03 07:55 UTC, mikalstill commented on shakenfist/images.py
> +        # Handle URL shortcut with built-in , '
Great moments in search and replace.

2021-05-03 08:39 UTC, mandoonandy approved these changes
LGTM

2021-05-03 08:49 UTC, merged